---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: k0rdent-configuration
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/Algeran/k0rdent-fluxcd.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k0rdent-platform
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./management/k0rdent/platform
  prune: true
  sourceRef:
    kind: GitRepository
    name: k0rdent-configuration
    namespace: flux-system
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: managements.k0rdent.mirantis.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: accessmanagements.k0rdent.mirantis.com
    - apiVersion: apps/v1
      kind: Deployment
      name: kcm-controller-manager
      namespace: kcm-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k0rdent-configuration
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./management/k0rdent/configuration
  prune: true
  sourceRef:
    kind: GitRepository
    name: k0rdent-configuration
    namespace: flux-system
  dependsOn:
    - name: k0rdent-platform

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: provider-credentials
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./credentials
  prune: true
  sourceRef:
    kind: GitRepository
    name: k0rdent-configuration
    namespace: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-deployments
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters
  prune: true
  sourceRef:
    kind: GitRepository
    name: k0rdent-configuration
    namespace: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: global-services
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./global-services
  prune: true
  sourceRef:
    kind: GitRepository
    name: k0rdent-configuration
    namespace: flux-system